name: side_sheet_material3
description: This Flutter package provides a Material Design 3 modal side sheet widget.
version: 0.0.2
repository: https://github.com/egortabula/side_sheet_material3
issue_tracker: https://github.com/egortabula/side_sheet_material3/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
screenshots:
  - description: 'This screenshot shows the thumbnail of the package'
    path: assets/Material design 3 side sheet.jpg

environment:
  sdk: '>=2.19.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  flutter:
    sdk: flutter

